const fs=require('fs'),path=require('path'),today=new Date().toISOString().slice(0,10),slug=today;
const feed=JSON.parse(fs.readFileSync(path.join(__dirname,'..','feed.json'),'utf8'));
if(feed.posts.find(p=>p.slug===slug)){console.log('Exists');process.exit(0)}
const pool=[[["狗狗拉稀的常见原因和在家处理方法","观察便便颜色和状态。禁食12小时+补充益生菌。拉血或精神不好马上去医院。","狗狗健康"],["金毛犬的日常护理要点：掉毛、运动和饮食","金毛掉毛量大，每天梳毛是必须的。每天至少1小时运动。髋关节问题是遗传病要注意。","金毛"],["小狗到家第一天：新主人必做的5件事","准备狗窝狗粮水碗、划定活动区域、不要洗澡、带去看兽医、开始建立规律。","新手养狗"]],[["泰迪犬的毛发打理：不褪色不掉毛的秘诀","泰迪不掉毛但要定期修剪。耳朵容易发炎要常清理。泪痕问题用温水每天擦。","泰迪"],["狗狗乱叫怎么办？不同原因的不同纠正方法","无聊叫、警戒叫、分离焦虑叫、兴奋叫。每种原因处理方式完全不同，先判断再纠正。","行为训练"],["狗狗疫苗怎么打？幼犬到成犬的完整接种时间表","6-8周第一针，之后每3-4周一针到16周。狂犬疫苗每年一次。抗体检测可替代部分疫苗。","预防保健"]],[["柯基犬饲养指南：短腿也有大讲究","柯基容易发胖要控制饮食。腰椎问题不能频繁爬楼梯。聪明但倔强需要耐心训练。","柯基"],["狗狗吃什么狗粮好？成分表怎么看","前三位是肉而不是谷物。蛋白质至少25%。不同年龄段和体型的狗粮选择不同。","饮食营养"],["狗狗的分离焦虑：识别和改善方法","独自在家狂叫、拆家、随地大小便。逐步训练+留玩具+不要回家时过度兴奋。","行为训练"]],[["哈士奇的饲养注意事项：拆家和掉毛","哈士奇精力旺盛每天至少2小时运动。掉毛季=一年两次一次半年。笼养训练很重要。","哈士奇"],["狗狗中暑急救和夏季防护指南","不要把狗留在车内！中暑症状：张口呼吸、流口水、走路不稳。立即降温+送医。","紧急处理"],["狗狗刷牙的正确方法：预防牙结石","从幼犬开始适应。用狗狗专用牙膏（人用的不行）。每周至少刷2-3次。","日常护理"]],[["狗狗出门爆冲的训练：P绳正确使用方法","P绳要戴在耳朵后面的位置。狗往前冲时轻轻提一下绳子。奖励在身边的时刻。","行为训练"],["老年犬的护理：7岁以上狗狗的注意事项","关节保健加葡萄糖胺。减少热量摄入防止肥胖。定期体检血液生化+心脏检查。","老年护理"],["比熊犬的泪痕问题：原因和彻底解决方案","食物过敏、鼻泪管堵塞、眼部感染都可能导致。换低敏粮+每天擦眼睛+剪短眼周毛发。","常见问题"]],[["狗狗皮肤病大全：真菌螨虫湿疹怎么区分","脱毛红疹瘙痒皮屑。不同病因用药完全不同。带去兽医做皮肤刮片确诊再用药。","疾病防治"],["狗狗护食怎么纠正：从幼犬开始训练","用手喂食建立信任。慢慢靠近食盆加更美味的食物。不要惩罚护食行为会加重。","行为训练"],["冬天遛狗注意事项：防寒防冻防盐","短毛狗出门穿衣服。爪子回来后要擦拭除雪盐。天冷运动量可适当减少。","日常护理"]],[["狗狗可以吃的水果和绝对不能吃的食物","苹果去核可以吃、蓝莓好。葡萄和葡萄干绝对不能吃会导致肾衰竭。洋葱巧克力致命。","饮食营养"],["狗狗托运全攻略：飞机火车汽车怎么带狗","检疫证明+航空箱+提前一个月准备。航空托运要确认航空公司有有氧舱。","实用攻略"],["自制狗狗零食：鸡肉干和红薯干的做法","鸡胸肉切薄片70度烘干6小时。无添加剂比买的健康便宜。可以加胡萝卜和南瓜。","饮食营养"]],[["狗狗突然跛行怎么办？可能是这几种原因","指甲太长、脚垫划伤、关节炎、韧带撕裂。先检查脚底有没有异物。持续跛行要拍X光。","紧急处理"],["如何让狗狗和猫咪和平相处：引入新宠物的步骤","隔离→气味交换→隔着门见面→同时喂食→短时接触→延长相处。耐心至少2周。","行为训练"],["狗狗的社交化训练：黄金期在16周前","3-16周让狗狗接触不同的人狗环境声音。错过了也不要急可以慢慢补但需要更多耐心。","行为训练"]]];
const idx=(new Date().getDate()-1)%pool.length,items=pool[idx];
const postTitle=items[0].tag+' | '+today;
feed.posts.unshift({slug,date:today,title:postTitle,items:items.map(i=>({title:i[0],desc:i[1],tag:i[2]}))});
feed.updated=today;
fs.writeFileSync(path.join(__dirname,'..','feed.json'),JSON.stringify(feed,null,2));
const html='<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>'+postTitle+'</title><style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}:root{--bg:#fafafa;--card:#fff;--text:#1a1a2e;--t2:#666;--accent:#ea580c;--border:#e5e7eb;--r:10px}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans SC",sans-serif;background:var(--bg);color:var(--text);line-height:1.7}.container{max-width:800px;margin:0 auto;padding:0 20px}header{background:var(--card);border-bottom:1px solid var(--border);padding:20px 0;margin-bottom:32px}header a{color:var(--accent);text-decoration:none;font-size:.9rem}header h1{font-size:1.3rem;margin-top:8px}.post{background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:28px}.post .date{color:var(--t2);font-size:.8rem;margin-bottom:20px}.entry{margin-bottom:24px;padding-bottom:20px;border-bottom:1px solid var(--border)}.entry:last-child{border-bottom:none}.entry h3{font-size:1rem;margin-bottom:4px}.entry p{color:var(--t2);font-size:.9rem}.tag{display:inline-block;font-size:.72rem;padding:2px 8px;border-radius:10px;margin-left:6px;background:var(--bg);color:var(--accent)}footer{text-align:center;padding:32px 20px;color:var(--t2);font-size:.8rem}@media(max-width:600px){.post{padding:18px}}</style></head><body><header><div class="container"><a href="../index.html">← 首页</a><h1>'+postTitle+'</h1></div></header><main class="container"><article class="post"><div class="date">📅 '+today+'</div>'+items.map(i=>'<div class="entry"><h3>'+i[0]+' <span class="tag">'+i[2]+'</span></h3><p>'+i[1]+'</p></div>').join('')+'</article></main><footer><p>每日更新</p></footer></body></html>';
fs.writeFileSync(path.join(__dirname,'..','posts',slug+'.html'),html);
console.log('Generated:',postTitle);
